-- Membuat Database
CREATE DATABASE kasir_resto;
USE kasir_resto;

-- Membuat Tabel menu
CREATE TABLE menu (
    idmenu BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Namamenu VARCHAR(255) NOT NULL,
    Harga INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Membuat Tabel users
CREATE TABLE users (
    iduser BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nama VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    level ENUM('admin', 'waiter', 'kasir', 'owner') NOT NULL,
    remember_token VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Membuat Tabel pelanggan
CREATE TABLE pelanggan (
    idpelanggan BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Namapelanggan VARCHAR(255) NOT NULL,
    Jeniskelamin ENUM('laki-laki', 'perempuan') NOT NULL,
    Nohp VARCHAR(255),
    alamat VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Membuat Tabel meja
CREATE TABLE meja (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Nomeja INT NOT NULL,
    status ENUM('kosong', 'terpakai') DEFAULT 'kosong',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Membuat Tabel pesanan
CREATE TABLE pesanan (
    idpesanan BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    idmenu BIGINT UNSIGNED NOT NULL,
    kode_pesanan VARCHAR(25) NOT NULL,
    idpelanggan BIGINT UNSIGNED NOT NULL,
    jumlah INT NOT NULL,
    iduser BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    meja_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (idmenu) REFERENCES menu(idmenu) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idpelanggan) REFERENCES pelanggan(idpelanggan) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (iduser) REFERENCES users(iduser) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (meja_id) REFERENCES meja(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Membuat Tabel transaksi
CREATE TABLE transaksi (
    idtransaksi BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    idpesanan BIGINT UNSIGNED NOT NULL,
    total INT NOT NULL,
    bayar INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    kembalian BIGINT GENERATED ALWAYS AS (bayar - total) STORED,
    Kurang BIGINT GENERATED ALWAYS AS (total - bayar) STORED,
    FOREIGN KEY (idpesanan) REFERENCES pesanan(idpesanan) ON DELETE CASCADE ON UPDATE CASCADE
);